name: bmi_calculator
description: A powerful BMI Calculator - Metric and Imperial

version: 1.1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  easy_localization: ^2.3.2
  flare_splash_screen: ^3.0.1
  bot_toast: ^3.0.0
  get: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/animations/
